### PR TITLE
Add `LightGBM` benchmark

### PR DESCRIPTION
**Pull request by xnuohz**
The result `{best_test_metric}±0.000 ({total_time}s)` is from the training log. Is this right?

### CODE REVIEW

**Comment by weihua916** [comment]
Thank you! Looks great.

> The result {best_test_metric}±0.000 ({total_time}s) is from the training log. Is this right?

Yes, that's right. Below is my script
```
result = torch.load(os.path.join(dir, f'{model}.pt'))
mean = result['best_test_metric']
if 'best_test_metrics' in result:
    std = result['best_test_metrics'].std()
else:
    std = 0
time = result['total_time']
text = f"{mean:.3f}±{std:.3f} ({time:.0f}s)"
```

**Review by weihua916 — APPROVED** [review]
LGTM after addressing https://github.com/pyg-team/pytorch-frame/pull/263#issuecomment-1837634447

**Comment by xnuohz** [comment]
@weihua916 @yiweny Done.

**Comment by weihua916** [comment]
Thank you!

**Pull request merged**
